# 数据相关配置
data:
  data_dir: "path/to/data"
  image_size: [256, 256]
  batch_size: 8
  num_workers: 8
  pin_memory: true
  persistent_workers: true

# 模型配置
model:
  name: "unet"
  params:
    image_shape: [3, 256, 256]
    base_channels: 128
    channel_mults: [1, 2, 2, 2]
    attention_resolutions: [16]
    num_heads: 8
    dropout: 0.1

# SDE配置
sde:
  name: "vp_sde"  # 可选: "vp_sde", "ve_sde", "subvp_sde"
  params:
    beta_min: 0.1
    beta_max: 20.0
    num_scales: 1000

# 训练配置
training:
  # 优化器设置
  optimizer:
    name: "Adam"
    lr: 1.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.0

  # EMA设置
  ema_decay: 0.999
  
  # 训练循环设置
  max_steps: 10000
  precision: "16-mixed"
  log_every_n_steps: 10
  sample_every_n_steps: 1000
  val_check_interval: 1000
  
  # 检查点设置
  checkpoint:
    save_top_k: 3
    monitor: "val_loss"
    mode: "min"
    dirpath: "checkpoints"
    filename: "score-model-{step:06d}"

# 日志配置
logging:
  name: "sde_training"
  save_dir: "logs"

# 其他设置
seed: 42 